# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoScanGui.ui'
#
# Created: Wed Sep 14 11:24:48 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 450)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumSize(QtCore.QSize(450, 450))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("clarity.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mysqlFrame = QtGui.QGroupBox(self.centralwidget)
        self.mysqlFrame.setGeometry(QtCore.QRect(10, 10, 431, 151))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.mysqlFrame.sizePolicy().hasHeightForWidth())
        self.mysqlFrame.setSizePolicy(sizePolicy)
        self.mysqlFrame.setObjectName("mysqlFrame")
        self.serverNameBox = QtGui.QLineEdit(self.mysqlFrame)
        self.serverNameBox.setGeometry(QtCore.QRect(80, 30, 201, 27))
        self.serverNameBox.setReadOnly(True)
        self.serverNameBox.setObjectName("serverNameBox")
        self.dbNameBox = QtGui.QLineEdit(self.mysqlFrame)
        self.dbNameBox.setGeometry(QtCore.QRect(80, 70, 201, 27))
        self.dbNameBox.setReadOnly(True)
        self.dbNameBox.setObjectName("dbNameBox")
        self.userNameBox = QtGui.QLineEdit(self.mysqlFrame)
        self.userNameBox.setGeometry(QtCore.QRect(80, 110, 131, 27))
        self.userNameBox.setReadOnly(True)
        self.userNameBox.setObjectName("userNameBox")
        self.passwordBox = QtGui.QLineEdit(self.mysqlFrame)
        self.passwordBox.setGeometry(QtCore.QRect(282, 110, 131, 27))
        self.passwordBox.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordBox.setReadOnly(True)
        self.passwordBox.setObjectName("passwordBox")
        self.label = QtGui.QLabel(self.mysqlFrame)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.mysqlFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 67, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.mysqlFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.mysqlFrame)
        self.label_4.setGeometry(QtCore.QRect(230, 110, 41, 20))
        self.label_4.setObjectName("label_4")
        self.lockBox = QtGui.QCheckBox(self.mysqlFrame)
        self.lockBox.setGeometry(QtCore.QRect(320, 30, 61, 22))
        self.lockBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lockBox.setChecked(True)
        self.lockBox.setObjectName("lockBox")
        self.saveButton = QtGui.QPushButton(self.mysqlFrame)
        self.saveButton.setGeometry(QtCore.QRect(310, 70, 85, 27))
        self.saveButton.setObjectName("saveButton")
        self.meteoScanFrame = QtGui.QGroupBox(self.centralwidget)
        self.meteoScanFrame.setGeometry(QtCore.QRect(10, 180, 431, 101))
        self.meteoScanFrame.setObjectName("meteoScanFrame")
        self.startButton = QtGui.QPushButton(self.meteoScanFrame)
        self.startButton.setGeometry(QtCore.QRect(20, 60, 98, 27))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtGui.QPushButton(self.meteoScanFrame)
        self.stopButton.setGeometry(QtCore.QRect(160, 60, 98, 27))
        self.stopButton.setObjectName("stopButton")
        self.minimizeButton = QtGui.QPushButton(self.meteoScanFrame)
        self.minimizeButton.setGeometry(QtCore.QRect(300, 60, 98, 27))
        self.minimizeButton.setObjectName("minimizeButton")
        self.label_5 = QtGui.QLabel(self.meteoScanFrame)
        self.label_5.setGeometry(QtCore.QRect(250, 20, 89, 17))
        self.label_5.setObjectName("label_5")
        self.pollInterval = QtGui.QLineEdit(self.meteoScanFrame)
        self.pollInterval.setGeometry(QtCore.QRect(350, 20, 31, 21))
        self.pollInterval.setEchoMode(QtGui.QLineEdit.Normal)
        self.pollInterval.setReadOnly(True)
        self.pollInterval.setObjectName("pollInterval")
        self.textBox = QtGui.QTextEdit(self.centralwidget)
        self.textBox.setGeometry(QtCore.QRect(13, 307, 421, 131))
        self.textBox.setReadOnly(True)
        self.textBox.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>")
        self.textBox.setObjectName("textBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MeteoScan", None, QtGui.QApplication.UnicodeUTF8))
        self.mysqlFrame.setTitle(QtGui.QApplication.translate("MainWindow", "Database Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "db name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "user:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "pass:", None, QtGui.QApplication.UnicodeUTF8))
        self.lockBox.setText(QtGui.QApplication.translate("MainWindow", "lock", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.meteoScanFrame.setTitle(QtGui.QApplication.translate("MainWindow", "Meteo Scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.minimizeButton.setText(QtGui.QApplication.translate("MainWindow", "Systray", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "time interval:", None, QtGui.QApplication.UnicodeUTF8))

